version: "3.8"
services:
  db:
    image: postgres:13.0
    volumes:
      - kurisudb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kurisu"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_user
      - db_password
    restart: always

  kurisu:
    image: ghcr.io/nh-server/kurisu
    volumes:
      - /opt/kurisudata:/home/kurisu/data
    command: python3 databaseconverter.py
    environment:
      DB_USER: /run/secrets/db_user
      DB_PASSWORD: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    depends_on:
      db:
        condition: service_healthy

volumes:
  kurisudb:

secrets:
  db_user:
    file: /opt/secrets/kurisu/db_user
  db_password:
    file: /opt/secrets/kurisu/db_password
