version: "3.8"
services:
  db:
    image: postgres:13.0
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    restart: always

  kurisu:
    image: ghcr.io/nh-server/kurisu
    volumes:
      - ./kurisu-data:/home/kurisu/data
    restart: always

secrets:
  db_user:
    file: /opt/secrets/kurisu/db_user
  db_password:
    file: /opt/secrets/kurisu/db_password
  db_name:
    file: /opt/secrets/kurisu/db_name